package com.hzy.greendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hzy.greendao.Task;
import com.hzy.greendao.City;

import com.hzy.greendao.greendao.TaskDao;
import com.hzy.greendao.greendao.CityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig cityDaoConfig;

    private final TaskDao taskDao;
    private final CityDao cityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(City.class, cityDao);
    }
    
    public void clear() {
        taskDaoConfig.clearIdentityScope();
        cityDaoConfig.clearIdentityScope();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

}
